### ISSUE TITLE
IndeX Error and VPN

### ISSUE THREAD

**Issue by XwZHybrid** [apersongithub/ABS-X#1]
the bot stops at some point before trying to switch vpn this the error:
list index out of range
File:"my location file for abs.py"
line179, in <module> driver.switch_to.window(driver.window_handles[1])

**Comment by beenruuu** [comment]
and have you found any way to fix it? if so let me know i have the same problem

**Comment by apersongithub** [comment]
known bug will fix next week

**Comment by beenruuu** [comment]
ok, thanks bro 😉

**Comment by beenruuu** [comment]
If you could create a discord server where you notify us of each update of the files, it would help me a lot, thanks in advance!

**Comment by apersongithub** [comment]
https://discord.gg/xdwVuz3q
